sudo: false
language: go

go:
  - 1.7
  - 1.7.3
  - 1.7.4
  - 1.7.5
  - 1.7.6
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.8.4
  - 1.8.5
  - 1.9
  - 1.9.1
  - 1.9.2

go_import_path: github.com/golang/dep

env:
  - DEP_VERSION="0.3.2"

before_install:
  - export GO15VENDOREXPERIMENT="1"

script:
  - go test ./... -v -cover -race

notifications:
  email:
    - kranz@null.net