sudo: false
language: go

go_import_path: github.com/golang/dep

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

before_script:
  - go vet ./...
  - go get -u github.com/golang/dep
  - dep ensure

go:
  - 1.7
  - 1.7.3
  - 1.7.4
  - 1.7.5
  - 1.7.6
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.8.4
  - 1.8.5
  - 1.9
  - 1.9.1
  - 1.9.2

before-script:

script: go test ./... -v -cover -race

notifications:
  email:
    - kranz@null.net