sudo: false
language: go

install:
  go get -u github.com/golang/dep

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.6
  - 1.7
  - 1.7.3
  - 1.7.4
  - 1.7.5
  - 1.7.6
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.8.4
  - 1.8.5
  - 1.9
  - 1.9.1
  - 1.9.2

before_script: dep ensure

script: go test ./... -v -cover -race

notifications:
  email:
    - kranz@null.net